name: MyEssentials
version: '${project.version}'
main: com.marcusjohansen.myessentials.MyEssentials
api-version: 1.19
authors: [ Mommotexx ]
description: My essential plugin for Minecraft 1.19.2
website: https://github.com/mommotexx
commands:
  feed:
    description: Feeds the player
    usage: /<command>
    permission: myessentials.feed
permissions:
  myessentials.feed:
    description: Allows feed command
    default: op
  myessentials.*:
    description: Wildcard permission
    default: op
    children:
      myessentials.feed: true